# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libwebqqpython', [dirname(__file__)])
        except ImportError:
            import _libwebqqpython
            return _libwebqqpython
        if fp is not None:
            try:
                _mod = imp.load_module('_libwebqqpython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libwebqqpython = swig_import_helper()
    del swig_import_helper
else:
    import _libwebqqpython
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


class Action(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Action, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Action, name)
    __repr__ = _swig_repr
    def run(self): return _libwebqqpython.Action_run(self)
    __swig_destroy__ = _libwebqqpython.delete_Action
    __del__ = lambda self : None;
    def __init__(self): 
        if self.__class__ == Action:
            _self = None
        else:
            _self = self
        this = _libwebqqpython.new_Action(_self, )
        try: self.this.append(this)
        except: self.this = this
    def __disown__(self):
        self.this.disown()
        _libwebqqpython.disown_Action(self)
        return weakref_proxy(self)
Action_swigregister = _libwebqqpython.Action_swigregister
Action_swigregister(Action)

class Caller(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Caller, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Caller, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libwebqqpython.new_Caller()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libwebqqpython.delete_Caller
    __del__ = lambda self : None;
    def delAction(self): return _libwebqqpython.Caller_delAction(self)
    def setAction(self, *args): return _libwebqqpython.Caller_setAction(self, *args)
    def call(self): return _libwebqqpython.Caller_call(self)
Caller_swigregister = _libwebqqpython.Caller_swigregister
Caller_swigregister(Caller)

# This file is compatible with both classic and new-style classes.


